# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: orderbook.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0forderbook.proto\x12\torderbook\"\x1f\n\rSymbolRequest\x12\x0e\n\x06symbol\x18\x01 \x01(\t\"=\n\nPriceLevel\x12\x0e\n\x06symbol\x18\x01 \x01(\t\x12\r\n\x05price\x18\x02 \x01(\x01\x12\x10\n\x08quantity\x18\x03 \x01(\x01\"J\n\x0eSpreadResponse\x12\x0e\n\x06symbol\x18\x01 \x01(\t\x12\x0b\n\x03\x62id\x18\x02 \x01(\x01\x12\x0b\n\x03\x61sk\x18\x03 \x01(\x01\x12\x0e\n\x06spread\x18\x04 \x01(\x01\"\x8e\x01\n\x10SnapshotResponse\x12\x0e\n\x06symbol\x18\x01 \x01(\t\x12\x10\n\x08\x62\x65st_bid\x18\x02 \x01(\x01\x12\x10\n\x08\x62\x65st_ask\x18\x03 \x01(\x01\x12\x0e\n\x06spread\x18\x04 \x01(\x01\x12\x0f\n\x07\x62id_qty\x18\x05 \x01(\x01\x12\x0f\n\x07\x61sk_qty\x18\x06 \x01(\x01\x12\x14\n\x0clast_updated\x18\x07 \x01(\x01\x32\x98\x02\n\x10OrderBookService\x12=\n\nGetBestBid\x12\x18.orderbook.SymbolRequest\x1a\x15.orderbook.PriceLevel\x12=\n\nGetBestAsk\x12\x18.orderbook.SymbolRequest\x1a\x15.orderbook.PriceLevel\x12@\n\tGetSpread\x12\x18.orderbook.SymbolRequest\x1a\x19.orderbook.SpreadResponse\x12\x44\n\x0bGetSnapshot\x12\x18.orderbook.SymbolRequest\x1a\x1b.orderbook.SnapshotResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'orderbook_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SYMBOLREQUEST']._serialized_start=30
  _globals['_SYMBOLREQUEST']._serialized_end=61
  _globals['_PRICELEVEL']._serialized_start=63
  _globals['_PRICELEVEL']._serialized_end=124
  _globals['_SPREADRESPONSE']._serialized_start=126
  _globals['_SPREADRESPONSE']._serialized_end=200
  _globals['_SNAPSHOTRESPONSE']._serialized_start=203
  _globals['_SNAPSHOTRESPONSE']._serialized_end=345
  _globals['_ORDERBOOKSERVICE']._serialized_start=348
  _globals['_ORDERBOOKSERVICE']._serialized_end=628
# @@protoc_insertion_point(module_scope)

