# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import orderbook_pb2 as orderbook__pb2

GRPC_GENERATED_VERSION = '1.64.1'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in orderbook_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class OrderBookServiceStub(object):
    """── SERVICE DEFINITION ────────────────────────────────────────────
    This is the API — what functions can be called on the server.
    Any service in our system can call these by importing the generated stub.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetBestBid = channel.unary_unary(
                '/orderbook.OrderBookService/GetBestBid',
                request_serializer=orderbook__pb2.SymbolRequest.SerializeToString,
                response_deserializer=orderbook__pb2.PriceLevel.FromString,
                _registered_method=True)
        self.GetBestAsk = channel.unary_unary(
                '/orderbook.OrderBookService/GetBestAsk',
                request_serializer=orderbook__pb2.SymbolRequest.SerializeToString,
                response_deserializer=orderbook__pb2.PriceLevel.FromString,
                _registered_method=True)
        self.GetSpread = channel.unary_unary(
                '/orderbook.OrderBookService/GetSpread',
                request_serializer=orderbook__pb2.SymbolRequest.SerializeToString,
                response_deserializer=orderbook__pb2.SpreadResponse.FromString,
                _registered_method=True)
        self.GetSnapshot = channel.unary_unary(
                '/orderbook.OrderBookService/GetSnapshot',
                request_serializer=orderbook__pb2.SymbolRequest.SerializeToString,
                response_deserializer=orderbook__pb2.SnapshotResponse.FromString,
                _registered_method=True)


class OrderBookServiceServicer(object):
    """── SERVICE DEFINITION ────────────────────────────────────────────
    This is the API — what functions can be called on the server.
    Any service in our system can call these by importing the generated stub.
    """

    def GetBestBid(self, request, context):
        """Get the current best bid (highest buy price) for a symbol
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBestAsk(self, request, context):
        """Get the current best ask (lowest sell price) for a symbol
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSpread(self, request, context):
        """Get bid, ask, and spread together in one call
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSnapshot(self, request, context):
        """Get full snapshot: bid, ask, spread, quantities, timestamp
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OrderBookServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetBestBid': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBestBid,
                    request_deserializer=orderbook__pb2.SymbolRequest.FromString,
                    response_serializer=orderbook__pb2.PriceLevel.SerializeToString,
            ),
            'GetBestAsk': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBestAsk,
                    request_deserializer=orderbook__pb2.SymbolRequest.FromString,
                    response_serializer=orderbook__pb2.PriceLevel.SerializeToString,
            ),
            'GetSpread': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSpread,
                    request_deserializer=orderbook__pb2.SymbolRequest.FromString,
                    response_serializer=orderbook__pb2.SpreadResponse.SerializeToString,
            ),
            'GetSnapshot': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSnapshot,
                    request_deserializer=orderbook__pb2.SymbolRequest.FromString,
                    response_serializer=orderbook__pb2.SnapshotResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'orderbook.OrderBookService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('orderbook.OrderBookService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class OrderBookService(object):
    """── SERVICE DEFINITION ────────────────────────────────────────────
    This is the API — what functions can be called on the server.
    Any service in our system can call these by importing the generated stub.
    """

    @staticmethod
    def GetBestBid(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/orderbook.OrderBookService/GetBestBid',
            orderbook__pb2.SymbolRequest.SerializeToString,
            orderbook__pb2.PriceLevel.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBestAsk(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/orderbook.OrderBookService/GetBestAsk',
            orderbook__pb2.SymbolRequest.SerializeToString,
            orderbook__pb2.PriceLevel.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSpread(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/orderbook.OrderBookService/GetSpread',
            orderbook__pb2.SymbolRequest.SerializeToString,
            orderbook__pb2.SpreadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSnapshot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/orderbook.OrderBookService/GetSnapshot',
            orderbook__pb2.SymbolRequest.SerializeToString,
            orderbook__pb2.SnapshotResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


